bill/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search/', views.search_user, name="search_user"),
    path('display/<int:id>', views.display_users_bill, name="display_user"),
]

customer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.customer_search, name="customer_search"),
    
]

nea_bill_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('customer.urls')),
    path('', include(('customer.urls', 'customer'), namespace='customer')),    
    path('bill/', include(('bill.urls', 'bill'), namespace='bill')),    
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),    
    path('branch/', include('branch.urls')),
    path('demand/', include('demand.urls')),
    path('khalti/', include('khalti.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("payment_detail/<int:id>", views.payment_detail, name="payment_detail"),
    path("payment/<int:id>", views.payment, name="payment"),
    path("message/", views.message, name="message"),
    path("khalti_payment_verify/", views.khalti_payment_verify, name="khalti_payment_verify"),   
]

templates/adminsearch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Search User</title>
</head>
<body>
    <div class="form-container">
        <form method="POST" action="{% url 'bill:search_user' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Customer Name</label>
                <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" placeholder="Name">
                <!-- You can add additional HTML elements or custom styles here -->
            </div>
            <button type="submit" class="btn btn-outline-primary">Submit</button>
        </form>
    </div>
  
</body>
</html>

templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My App{% endblock %}</title>
    <!-- Add Bootstrap CSS -->
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}

    <!-- Add Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>    

</body>
</html>

templates/customerbill.html
{% extends 'base.html' %}

{% block content %}
<h2>{{customer.full_name}}</h2>


<table class="table">
    <thead>
        <tr>
            <th>S.N</th>
            <th>Bill No</th>
            <th>Bill Amount</th>
            <th>Bill Month</th>
            <th>Bill Year</th>
            <th>Current Reading</th>
            <th>Previous Reading</th>
            <th>Payment</th>
        </tr>
    </thead>
    <tbody>
        {% if bills %}
            {% for bill in bills %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{bill.id}}</td>
                    <td>{{bill.bill_amount}}</td>
                    <td>{{bill.bill_month}}</td>
                    <td>{{bill.bill_year}}</td>
                    <td>{{bill.current_reading}}</td>
                    <td>{{bill.prev_reading}}</td>
                    
                    <td>
                        {% if bill.payment_status %}
                            <a href={% url 'payment:payment_detail' bill.id%}>
                                Paid
                            </a>
                        {% else %}
                            <a href={% url 'payment:payment' bill.id%}>
                                Not Paid
                            </a>
                        {% endif %}
                    </td>
                    
                </tr>
            {% endfor %}

        {% else %}

        {% endif %}
    </tbody>
</table>

{% endblock content %}

templates/customerdisplay.html
{% extends 'base.html' %}

{% block content %}
    <h1>Customers List</h1>
        {% if customers %}
        
        <table class="table">
            <thead>
                <tr>
                    <th>S.N</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone Number</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}  
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>
                            <a href={% url 'bill:display_user' customer.id %} class="no-style"> {{ customer.full_name }}</a>
                        </td>
                        <td>{{ customer.address }}</td>
                        <td>{{ customer.mobile_no }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No customers found.</p>
    {% endif %}
{% endblock content %}

templates/customersearch.html
{% extends 'base.html' %}


{% block content %}
<div class="form-container">
    <form method="POST" action="{% url 'customer:customer_search' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Customer Name</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" placeholder="Name">
            <label for="{{ form.mobile_no.id_for_label }}">Mobile Number</label>
            <input type="text" class="form-control" id="{{ form.mobile_no.id_for_label }}" name="{{ form.mobile_no.html_name }}" placeholder="Mobile">
            <label for="{{ form.date_of_birth.id_for_label }}">Date of Birth</label>
            <input type="date" class="form-control" id="{{ form.date_of_birth.id_for_label }}" name="{{ form.date_of_birth.html_name }}" placeholder="date of birth">
            <!-- You can add additional HTML elements or custom styles here -->
        </div>
        <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>
</div>
{% endblock content %}

templates/displaybill.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{customer.full_name}}</h1>
    <hr>
        <h2>Bill</h2>
        {% if bills %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Bill No</th>
                        <th>Year</th>
                        <th>Month</th>
                        <th>Current Reading</th>
                        <th>Previous Reading</th>
                        <th>Bill Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bill in bills %}
                        <tr>
                            <td>{{bill.id}}</td>
                            <td>{{bill.bill_year}}</td>
                            <td>{{bill.bill_month}}</td>
                            <td>{{bill.current_reading}}</td>
                            <td>{{bill.prev_reading}}</td>
                            <td>{{bill.bill_amount}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No Bills</p>
            <hr>
        {% endif %}
        
        <h2>Payment</h2>    
        {% if payments %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Payment Date</th>
                        <th>Payment Amount</th>
                        <th>Rebeat Amount</th>
                        <th>Fine Amount</th>
                        <th>Bill No</th>
                    </tr>
                </thead>
                <tbody>
                    {% for payment in payments %}
                        <tr>
                            <td>{{payment.payment_date}}</td>
                            <td>{{payment.payment_amount}}</td>
                            <td>{{payment.rebeat_amount}}</td>
                            <td>{{payment.fine_amount}}</td>
                            <td>{{payment.bill.id}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No Payments</p>
        {% endif %}
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Home Page</h1>
</body>
</html>

templates/paymentdetails.html
{% extends 'base.html' %}

{% block content %}
{% if payments %}
    <dl class="row">
        {% for payment in  payments%}
            <dt class="col-sm-3">Bill No</dt>
            <dd class="col-sm-9">{{payment.bill_id}}</dd>
            <dt class="col-sm-3">Payment Amount</dt>
            <dd class="col-sm-9">{{payment.payment_amount}}</dd>
            <dt class="col-sm-3">Rebate Amount</dt>
            <dd class="col-sm-9">{{payment.rebeat_amount}}</dd>
            <dt class="col-sm-3">Fine Amount</dt>
            <dd class="col-sm-9">{{payment.fine_amount}}</dd>
            <dt class="col-sm-3">Payment Date</dt>
            <dd class="col-sm-9">{{payment.payment_date}}</dd>
            <dt class="col-sm-3">Payment Option Used</dt>
            <dd class="col-sm-9">{{payment.payment_option.name}}</dd>
        {% endfor %}
  </dl>
{% else %}
  Payment Not found
{% endif %}
{% endblock content %}

templates/paymentmessage.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}
      <a href="/">
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
      </a>
    {% endif %}
      
{% endblock content %}

templates/unpaidpayments.html
{% extends 'base.html' %}

{% block content %}
<script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
{% if bills %}
    <dl class="row">
        {% for bill in  bills%}
            <dt class="col-sm-3">Bill No</dt>
            <dd class="col-sm-9">{{bill.id}}</dd>
            <dt class="col-sm-3">Bill Amount</dt>
            <dd class="col-sm-9">{{bill.bill_amount}}</dd>
            <dt class="col-sm-3">Current Reading</dt>
            <dd class="col-sm-9">{{bill.current_reading}}</dd>
            <dt class="col-sm-3">Previous Reading</dt>
            <dd class="col-sm-9">{{bill.prev_reading}}</dd>
            <dt class="col-sm-3">Payment Option</dt>
            <dd class="col-sm-9">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Payment Options
                    </button>
                    <ul class="dropdown-menu">
                      <li><button class="dropdown-item" id="payment-button" >KHALTI</button></li>
                      <li><a class="dropdown-item" href="#">eSewa</a></li>
                      <li><a class="dropdown-item" href="#">fone Pay</a></li>
                    </ul>
                  </div>
            </dd>
            <input type="hidden" id="bill-id" value="{{ bill.id }}">
            <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
            <script>
                var config = {
                    // replace the publicKey with yours
                    "publicKey": "test_public_key_2714765a49ac4507865f6be573e779a1",
                    "productIdentity": {{bill.id}},
                    "productName": {{bill.id}},
                    "productUrl": "http://127.0.0.1:8000/",
                    "paymentPreference": [
                        "KHALTI",
                        "EBANKING",
                        "MOBILE_BANKING",
                        "CONNECT_IPS",
                        "SCT",
                        ],
                    "eventHandler": {
                        onSuccess (payload) {
                            // hit merchant api for initiating verfication
                            console.log(payload);
                            axios.defaults.baseURL = 'http://127.0.0.1:8000/';
                            var billId = document.getElementById("bill-id").value;
                            axios.get("{% url 'payment:khalti_payment_verify' %}",{
                                params: {
                                    "token": payload.token,
                                    "bill_id": billId,
                                    "amount": payload.amount,
                                }
                            }).then(function(resp){
                                console.log(resp.data)
                                window.location.href = "{% url 'payment:message' %}";
                            })
                        },
                        onError (error) {
                            console.log(error);
                        },
                        onClose () {
                            console.log('widget is closing');
                        }
                    }
                };
        
                var checkout = new KhaltiCheckout(config);
                var btn = document.getElementById("payment-button");
                btn.onclick = function () {
                    // minimum transaction amount must be 10, i.e 1000 in paisa.
                    checkout.show({amount: {{bill.bill_amount}}*100});
                }
            </script>
        {% endfor %}
  </dl>
{% else %}
  Bill Not found
{% endif %}

{% if messages %}
      <div class="alert alert-primary" role="alert">
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
      </div>
{% endif %}
{% endblock content %}